### ISSUE TITLE
Conversion error

### ISSUE THREAD

**Issue by damiencarol** [jpmml/jpmml-xgboost#10]
I had this with a model from 0.40:
```
Exception in thread "main" org.jpmml.evaluator.TypeCheckException: Expected FLOAT, but got DOUBLE (-1.1199469541970004)
	at org.jpmml.evaluator.TypeUtil.toFloat(TypeUtil.java:456)
	at org.jpmml.evaluator.TypeUtil.cast(TypeUtil.java:330)
	at org.jpmml.evaluator.TypeUtil.parseOrCast(TypeUtil.java:61)
	at org.jpmml.evaluator.FieldValueUtil.create(FieldValueUtil.java:78)
	at org.jpmml.evaluator.FieldValueUtil.create(FieldValueUtil.java:45)
	at org.jpmml.evaluator.OutputUtil.evaluate(OutputUtil.java:297)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:117)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:85)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluateSegmentation(MiningModelEvaluator.java:424)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluateRegression(MiningModelEvaluator.java:123)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:104)
	at org.jpmml.evaluator.MiningModelEvaluator.evaluate(MiningModelEvaluator.java:85)
	at org.jpmml.evaluator.ModelEvaluator.evaluate(ModelEvaluator.java:79)
	at Main.main(Main.java:53)
```

I can create the PMML but the evaluator lost his mind.

**Comment by vruusmann** [comment]
What's your evaluator version? The conversion from `double` to `float` value space (loses numeric precision) has been enabled for quite some time.

**Comment by damiencarol** [comment]
evaluator version 1.1.20.
I fixed this by changing all types to double

**Comment by vruusmann** [comment]
> evaluator version 1.1.20.

That's a seriously outdated version. Please upgrade to 1.3.X, and this evaluation error will be gone.

> I fixed this by changing all types to double.

The XGBoost software operates with 32-bit floating point numbers. So, the use of the `float` data type is intentional.

**Comment by damiencarol** [comment]
thanks for your time @vruusmann 
The pb is that we have a Spark version only compatible with 1.1.x
