### ISSUE TITLE
xgb model with objective="rank:pairwise" cannot tranfrom to pmml

### ISSUE THREAD

**Issue by easonlv** [jpmml/jpmml-xgboost#16]
I have train a xgboost model with  objective="rank:pairwise" , it's ranking problem. Then I use the jpmml-xgboost to transfrom the file xgb.model to pmml file , get an error:
```
java -jar converter-executable-1.2-SNAPSHOT.jar --model-input xgb.model  --fmap-input fmap --pmml-output xgb.pmml
Exception in thread "main" java.lang.IllegalArgumentException: rank:pairwise
	at org.jpmml.xgboost.Learner.load(Learner.java:85)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:47)
	at org.jpmml.xgboost.Main.run(Main.java:123)
	at org.jpmml.xgboost.Main.main(Main.java:116)
```
Can you help me to solve it , thanks very much.

**Comment by vruusmann** [comment]
The `rank:pairwise` objective function is not supported at the moment.

**Comment by vruusmann** [comment]
Fixed in https://github.com/jpmml/jpmml-xgboost/commit/ed48853ecec46aaab2dccab4023b78f40070fcf4
