### ISSUE TITLE
Add support for the `dart` booster type

### ISSUE THREAD

**Issue by zx84289061** [jpmml/jpmml-xgboost#37]
```
Standard output is empty
Standard error:
May 13, 2019 4:20:27 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
May 13, 2019 4:20:27 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 49 ms.
May 13, 2019 4:20:27 PM org.jpmml.sklearn.Main run
INFO: Converting..
May 13, 2019 4:20:27 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: dart
	at org.jpmml.xgboost.Learner.load(Learner.java:99)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:53)
	at xgboost.sklearn.Booster.loadLearner(Booster.java:52)
	at xgboost.sklearn.Booster.getLearner(Booster.java:42)
	at xgboost.sklearn.BoosterUtil.getLearner(BoosterUtil.java:70)
	at xgboost.sklearn.BoosterUtil.getNumberOfFeatures(BoosterUtil.java:40)
	at xgboost.sklearn.XGBClassifier.getNumberOfFeatures(XGBClassifier.java:35)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:206)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IllegalArgumentException: dart
	at org.jpmml.xgboost.Learner.load(Learner.java:99)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:53)
	at xgboost.sklearn.Booster.loadLearner(Booster.java:52)
	at xgboost.sklearn.Booster.getLearner(Booster.java:42)
	at xgboost.sklearn.BoosterUtil.getLearner(BoosterUtil.java:70)
	at xgboost.sklearn.BoosterUtil.getNumberOfFeatures(BoosterUtil.java:40)
	at xgboost.sklearn.XGBClassifier.getNumberOfFeatures(XGBClassifier.java:35)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:206)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Traceback (most recent call last):
  File "tt.py", line 77, in <module>
    sklearn2pmml(pipeline,"./xgboost.pmml",with_repr = True)
  File "/data2/push_exec/tmp_x/lib/python3.6/site-packages/sklearn2pmml/__init__.py", line 252, in sklearn2pmml
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

**Comment by vruusmann** [comment]
Both `gbtree` and `dart` are decision tree-based booster types, so I assume that there are no major code changes necessary.

**Comment by zx84289061** [comment]
> Both `gbtree` and `dart` are decision tree-based booster types, so I assume that there are no major code changes necessary.

Because in my case , dart performs much better than gbtree so is there anyone can't update to support it ?

**Comment by vruusmann** [comment]
> it's appreciated that anyone can update to support it

I believe that if you add `case "dart"` right after `case "gbtree"` in this location (and then rebuild the JPMML-XGBoost library JAR file, and then drop it into SkLearn2PMML package's JARs directory), then it should work fine:
https://github.com/jpmml/jpmml-xgboost/blob/master/src/main/java/org/jpmml/xgboost/Learner.java#L94-L100

**Comment by zx84289061** [comment]
> > it's appreciated that anyone can update to support it
> 
> I believe that if you add `case "dart"` right after `case "gbtree"` in this location (and then rebuild the JPMML-XGBoost library JAR file, and then drop it into SkLearn2PMML package's JARs directory), then it should work fine:
> https://github.com/jpmml/jpmml-xgboost/blob/master/src/main/java/org/jpmml/xgboost/Learner.java#L94-L100

that looks really right good, but i train it in python , so how to change pip install source?

**Comment by zx84289061** [comment]
> > it's appreciated that anyone can update to support it
> 
> I believe that if you add `case "dart"` right after `case "gbtree"` in this location (and then rebuild the JPMML-XGBoost library JAR file, and then drop it into SkLearn2PMML package's JARs directory), then it should work fine:
> https://github.com/jpmml/jpmml-xgboost/blob/master/src/main/java/org/jpmml/xgboost/Learner.java#L94-L100

that's really nice ! thx so much!

**Comment by zx84289061** [comment]
> > it's appreciated that anyone can update to support it
> 
> I believe that if you add `case "dart"` right after `case "gbtree"` in this location (and then rebuild the JPMML-XGBoost library JAR file, and then drop it into SkLearn2PMML package's JARs directory), then it should work fine:
> https://github.com/jpmml/jpmml-xgboost/blob/master/src/main/java/org/jpmml/xgboost/Learner.java#L94-L100

i see u've done this issue and i clone the master code to build a new jar, then i run my py code , but i get this error msg:

Standard output is empty
Standard error:
May 14, 2019 8:05:53 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
May 14, 2019 8:05:53 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 53 ms.
May 14, 2019 8:05:53 PM org.jpmml.sklearn.Main run
INFO: Converting..
Exception in thread "main" java.lang.NoSuchMethodError: org.jpmml.xgboost.Learner.getNumFeatures()I
	at xgboost.sklearn.BoosterUtil.getNumberOfFeatures(BoosterUtil.java:42)
	at xgboost.sklearn.XGBClassifier.getNumberOfFeatures(XGBClassifier.java:35)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:206)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Traceback (most recent call last):
  File "tt.py", line 79, in <module>
    sklearn2pmml(pipeline,"./xgboost.pmml",with_repr = True)
  File "/lib/python3.6/site-packages/sklearn2pmml/__init__.py", line 252, in sklearn2pmml
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams

**Comment by vruusmann** [comment]
> I change the booster from dart to gbtree, is there something wrong?

I renamed some methods in the latest commit: https://github.com/jpmml/jpmml-xgboost/commit/a71d9e782a007630cb41da792e1cad85b99775fb

If you want to build a temporary JAR file, then you should use this commit instead: https://github.com/jpmml/jpmml-xgboost/commit/cf677e905bf0fd68d9d59c68a23287443d9301ec

Anyway, I'm expecting to release a new version of SkLearn2PMML package next week, which will combine all correct JAR file versions.

**Comment by zx84289061** [comment]
> > I change the booster from dart to gbtree, is there something wrong?
> 
> I renamed some methods in the latest commit: [a71d9e7](https://github.com/jpmml/jpmml-xgboost/commit/a71d9e782a007630cb41da792e1cad85b99775fb)
> 
> If you want to build a temporary JAR file, then you should use this commit instead: [cf677e9](https://github.com/jpmml/jpmml-xgboost/commit/cf677e905bf0fd68d9d59c68a23287443d9301ec)
> 
> Anyway, I'm expecting to release a new version of SkLearn2PMML package next week, which will combine all correct JAR file versions.
sorry to bother u, i get this wrong msg when i use the temporary jar by the commit_id cf677e9

Standard output is empty
Standard error:
May 15, 2019 3:04:27 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
May 15, 2019 3:04:27 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 49 ms.
May 15, 2019 3:04:27 PM org.jpmml.sklearn.Main run
INFO: Converting..
Exception in thread "main" java.lang.NoSuchMethodError: org.dmg.pmml.tree.Node.addNodes(Lorg/dmg/pmml/tree/Node;Lorg/dmg/pmml/tree/Node;)Lorg/dmg/pmml/tree/Node;
	at org.jpmml.xgboost.RegTree.encodeNode(RegTree.java:159)
	at org.jpmml.xgboost.RegTree.encodeNode(RegTree.java:151)
	at org.jpmml.xgboost.RegTree.encodeNode(RegTree.java:152)
	at org.jpmml.xgboost.RegTree.encodeNode(RegTree.java:152)
	at org.jpmml.xgboost.RegTree.encodeTreeModel(RegTree.java:93)
	at org.jpmml.xgboost.ObjFunction.createMiningModel(ObjFunction.java:80)
	at org.jpmml.xgboost.MultinomialLogisticRegression.encodeMiningModel(MultinomialLogisticRegression.java:54)
	at org.jpmml.xgboost.GBTree.encodeMiningModel(GBTree.java:77)
	at org.jpmml.xgboost.Learner.encodeMiningModel(Learner.java:154)
	at xgboost.sklearn.BoosterUtil.encodeBooster(BoosterUtil.java:58)
	at xgboost.sklearn.XGBClassifier.encodeModel(XGBClassifier.java:45)
	at xgboost.sklearn.XGBClassifier.encodeModel(XGBClassifier.java:27)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:213)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Traceback (most recent call last):
  File "tt.py", line 79, in <module>
    sklearn2pmml(pipeline,"./xgboost2.pmml",with_repr = True)

**Comment by vruusmann** [comment]
> sorry to bother u, i get this wrong msg when i use the temporary jar by the commit_id cf677e9
>
> Exception in thread "main" java.lang.NoSuchMethodError: 
> org.dmg.pmml.tree.Node.addNodes(Lorg/dmg/pmml/tree/Node;Lorg/dmg/pmml/tree/Node;)Lorg/dmg/pmml/tree/Node;
>	at org.jpmml.xgboost.RegTree.encodeNode(RegTree.java:159)

OK, I missed that - you'd need an updated JPMML-Model library JAR file (version 1.4.11) as well.

As suggested above, there will be an updated SkLearn2PMML package available soon (most likely, around the end of the next week).
