### ISSUE TITLE
model generated by treelite.export_as_xgboost can be loaded by xgb.booster but failed to be converted to pmml

### ISSUE THREAD

**Issue by littlebeanfang** [jpmml/jpmml-xgboost#39]
I generated a xgboost model file with treelite API export_as_xgboost. And I can load this model with xgb.booster. However, I failed to conver it to pmml with featuremap file. I think the binary model files may different,  but I cannot figure out what's the difference, should I skip an offset ?

[tgt1564479810692.model.zip](https://github.com/jpmml/jpmml-xgboost/files/3450160/tgt1564479810692.model.zip)

**Comment by littlebeanfang** [comment]
Here is the error message:

Exception in thread "main" java.io.IOException: Expected 29-element array of zeroes, got [0, 3, 0, 0, 0, 0, 0, 48, 91, 215862544, 32766, 0, 0, 0, 0, 110, 119, 0, 0, 215862543, 32766, 0, 0, 48, 91, 215862608, 32766, 124, 0]
	at org.jpmml.xgboost.XGBoostDataInput.readReserved(XGBoostDataInput.java:194)
	at org.jpmml.xgboost.Learner.load(Learner.java:67)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:53)
	at org.jpmml.xgboost.Main.run(Main.java:152)
	at org.jpmml.xgboost.Main.main(Main.java:143)

**Comment by vruusmann** [comment]
Note to self - should think about developing a Treelite-to-PMML converter.

**Comment by littlebeanfang** [comment]
solved by skip the empty check in readReserved, thanks~
