### ISSUE TITLE
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 166, Size: 95

### ISSUE THREAD

**Issue by songhuiming** [jpmml/jpmml-xgboost#44]
Hi everyone, 

when I try to convert the xgb model to pmml, I got this error. May I ask what happens here and how shall I fix this?

Thank you.

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 166, Size: 95
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at org.jpmml.converter.Schema.getFeature(Schema.java:126)
        at org.jpmml.xgboost.RegTree.encodeNode(RegTree.java:95)
        at org.jpmml.xgboost.RegTree.encodeNode(RegTree.java:135)
        at org.jpmml.xgboost.RegTree.encodeNode(RegTree.java:135)
        at org.jpmml.xgboost.RegTree.encodeNode(RegTree.java:135)
        at org.jpmml.xgboost.RegTree.encodeTreeModel(RegTree.java:77)
        at org.jpmml.xgboost.ObjFunction.createMiningModel(ObjFunction.java:80)
        at org.jpmml.xgboost.BinomialLogisticRegression.encodeMiningModel(BinomialLogisticRegression.java:42)
        at org.jpmml.xgboost.GBTree.encodeMiningModel(GBTree.java:74)
        at org.jpmml.xgboost.Learner.encodeMiningModel(Learner.java:160)
        at org.jpmml.xgboost.Learner.encodePMML(Learner.java:146)
        at org.jpmml.xgboost.Main.run(Main.java:170)
        at org.jpmml.xgboost.Main.main(Main.java:144)
```

**Comment by vruusmann** [comment]
> May I ask what happens here

It's clearly a mismatch between the XGBoost binary file, and the user-provided feature map file.

These two appear to be seriously mis-aligned (XGBoost binary file is referencing feature no. 166, but the feature map only contains 95 feature definition in total). Such mis-alignments are typically associated with categorical features.

> how shall I fix this?

Provide a correct feature map file.

Or use JPMML-XGBoost via R (https://github.com/jpmml/r2pmml) and/or Python wrappers (https://github.com/jpmml/sklearn2pmml), which generate correct feature map files automatically.

**Comment by liumy601** [comment]
@vruusmann is there a similar package in java like r2pmml and sklearn2pmml? i used xgboost4j-spark and also found this problem.

**Comment by vruusmann** [comment]
> is there a similar package in java like r2pmml and sklearn2pmml?

@liumy601 Have you seen the README file? The JPMML-XGBoost Java library/command-line application is exactly this.

> i used xgboost4j-spark and also found this problem.

Fix your Spark data schema specification. In any case, the problem is in your application code (not anywhere in the JPMML stack).

**Comment by liumy601** [comment]
> Fix your Spark data schema specification. In any case, the problem is in your application code (not anywhere in the JPMML stack).
I know the problem is caused by categorical features, so when export to pmml, i gave the whole schema which contains both origin categorical features and their one hot features, will this cause the schema problem? sorry, i'm not sure how to fix the spark schema specification.

**Comment by vruusmann** [comment]
> i'm not sure how to fix the spark schema specification.

@liumy601 Perhaps you should consult with the README file first:
https://github.com/jpmml/jpmml-sparkml-xgboost/blob/master/README.md#usage
