### ISSUE TITLE
Impossible to run sklearn2pmml 

### ISSUE THREAD

**Issue by sharonzagh** [jpmml/jpmml-xgboost#50]
Impossible to generate a pmml file with float features even though I am using the lastest version of sklearn2pmml (0.61.0)
I was able to generate a pmml file with the same dataframe if I just used features of type int instead of float

Error :  
```
Standard output is empty
Standard error:
Oct 13, 2020 11:47:51 AM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Oct 13, 2020 11:47:51 AM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 15 ms.
Oct 13, 2020 11:47:51 AM org.jpmml.sklearn.Main run
INFO: Converting..
Oct 13, 2020 11:47:51 AM sklearn2pmml.pipeline.PMMLPipeline initTargetFields
WARNING: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
Oct 13, 2020 11:47:51 AM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.NullPointerException
	at org.jpmml.xgboost.ObjFunction.createMiningModel(ObjFunction.java:98)
	at org.jpmml.xgboost.BinomialLogisticRegression.encodeMiningModel(BinomialLogisticRegression.java:47)
	at org.jpmml.xgboost.GBTree.encodeMiningModel(GBTree.java:74)
	at org.jpmml.xgboost.Learner.encodeMiningModel(Learner.java:246)
	at xgboost.sklearn.BoosterUtil.encodeBooster(BoosterUtil.java:59)
	at xgboost.sklearn.XGBClassifier.encodeModel(XGBClassifier.java:45)
	at xgboost.sklearn.XGBClassifier.encodeModel(XGBClassifier.java:27)
	at sklearn.Estimator.encode(Estimator.java:84)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:238)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)

Exception in thread "main" java.lang.NullPointerException
	at org.jpmml.xgboost.ObjFunction.createMiningModel(ObjFunction.java:98)
	at org.jpmml.xgboost.BinomialLogisticRegression.encodeMiningModel(BinomialLogisticRegression.java:47)
	at org.jpmml.xgboost.GBTree.encodeMiningModel(GBTree.java:74)
	at org.jpmml.xgboost.Learner.encodeMiningModel(Learner.java:246)
	at xgboost.sklearn.BoosterUtil.encodeBooster(BoosterUtil.java:59)
	at xgboost.sklearn.XGBClassifier.encodeModel(XGBClassifier.java:45)
	at xgboost.sklearn.XGBClassifier.encodeModel(XGBClassifier.java:27)
	at sklearn.Estimator.encode(Estimator.java:84)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:238)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)
```

Code that I am running:
```
y = [0,1,1,1,0,1,0,0,1,0]
simple_df = pd.DataFrame({'feature1':[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]})
recorder= DataFrameMapper([(["feature1"], None),])
pipeline = PMMLPipeline([
    ("mapper", recorder),
    ("classifier", XGBClassifier())
])
pipeline.fit(simple_df,y)
sklearn2pmml(pipeline, "pipeline.pmml")
```

**Comment by sharonzagh** [comment]
As I mentioned before, the version of Sklearn2PMML that I am using is the latest version, which is sklearn2pmml 0.61.0

**Comment by vruusmann** [comment]
Switch to SkLearn2PMML version 0.62.0!
