### ISSUE TITLE
Support for `reg:pseudohubererror` objective function

### ISSUE THREAD

**Issue by zhengwei14** [jpmml/jpmml-xgboost#59]
Caused by: java.lang.IllegalArgumentException: reg:pseudohubererror
	at org.jpmml.xgboost.Learner.parseObjective(Learner.java:410)
	at org.jpmml.xgboost.Learner.loadBinary(Learner.java:100)
	at org.jpmml.xgboost.Learner.loadBinary(Learner.java:195)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:94)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:60)

**Comment by vruusmann** [comment]
This objective is probably just a synonym for the plain `reg:linear` objective function?

Insert an appropriate case into this switch statement, rebuild and report back:
https://github.com/jpmml/jpmml-xgboost/blob/1.6.2/pmml-xgboost/src/main/java/org/jpmml/xgboost/Learner.java#L385-L410

**Comment by zhengwei14** [comment]
> This objective is probably just a synonym for the plain `reg:linear` objective function?
> 
> Insert an appropriate case into this switch statement, rebuild and report back: https://github.com/jpmml/jpmml-xgboost/blob/1.6.2/pmml-xgboost/src/main/java/org/jpmml/xgboost/Learner.java#L385-L410

I tried it , and it's working. would you be releasing a new version?
